### PR TITLE
Fix unfollowable paths in output messages

### LINKED ISSUE #41: File link is invalid when points to the Rust core
If panic is triggered by the Rust core or a standard library, the link to the source code in the error message is broken because it must be applied to the Rust source folder, but Atom Build applies it to our project folder.

The first thought is to analyse the presence of the `RUST_SRC_PATH` environment variable and combine it with the file path emitted by rustc in its error message. The indicator for the necessity of such modification is that the file name starts with '..'  I've got a working prototype, albeit more research must be done on the issue especially when multirust is used.

Unfortunately, Atom Build doesn't allow to omit the file link in the high-level messages, so if the environment variable is not set, we still have to produce the broken link.

Any thoughts?

### PR DESCRIPTION
**Pull request by alygin**
When a program panics the file link in the output message might point to the Rust core or a standard library. That happens, for instance, when the panic is caused by `unwrap()` or similar functions. In this case Linter ends up with a broken link. The PR fixes this problem in cases when the user has the `RUST_SRC_PATH` environment variable set.

The PR fixes #41 where additional details can be found.

It also fixes a problem that led to ignoring panics which description or thread name contained a single quote.

### CODE REVIEW

File: lib/cargo.js [hunk 1]
```diff
@@ -105,6 +106,18 @@ export function provideBuilder() {
         }
       }
 
+      // Checks if a file pointed by a message relates to the Rust source code and
+      // corrects it if needed and if possible
+      function normalizePath(path) {
+        if (rustSrcPath && path.length > 6) {
+          const prefix = path.substring(0, 7);
```
Comment (noseglid) [inline lib/cargo.js]: What are these magic numbers?

File: lib/cargo.js [hunk 2]
```diff
@@ -105,6 +106,18 @@ export function provideBuilder() {
...
+          if (prefix === '../src/' || prefix === '..\\src\\') {
```
Comment (noseglid) [inline lib/cargo.js]: What if source code is not put in a folder named `src` ?

Comment (alygin) [inline lib/cargo.js]: This function will work in such case because in the line 115 I get rid of `../src` completely and use the value of `RUST_SRC_PATH` instead as the base path.

And `../src` is emitted by rustc independently of one's source location, so I think we could rely on it as the marker.

File: lib/cargo.js (hunk 1 above)
Comment (alygin) [inline lib/cargo.js]: It's the length of the marker. I agree, they might be confusing here, I should use a named constant instead. I'll fix it.

Comment (alygin) [inline lib/cargo.js]: Done

**Comment by oli-obk** [comment]
needs a rebase

**Comment by alygin** [comment]
rebased
