### PR TITLE
fix cargo update with `--message-format`

### LINKED ISSUE #74: JSON error format used in cargo clean?
When "Use JSON error format" is active, this package tries to add the `--message-format` option to `cargo clean` as well, which doesn't work because the command doesn't support this option apparently:

```
$ cargo clean --message-format=json
error: Unknown flag: '--message-format'
 
Usage:
    cargo clean [options]
 ```

### PR DESCRIPTION
**Pull request by oli-obk**
`cargo update --message-format=json`

yields

```
error: Unknown flag: '--message-format'
 
Usage:
    cargo update [options]
```

fixes #74

### CODE REVIEW

**Comment by swsnr** [comment]
Oh, I hit the same issue with cargo clean, see #74

File: lib/cargo.js [hunk 1]
```diff
@@ -203,7 +203,7 @@ export function provideBuilder() {
         // Common build command parameters
         buildCfg.exec = atom.config.get('build-cargo.cargoPath');
         buildCfg.env = {};
-        if (atom.config.get('build-cargo.jsonErrorFormat')) {
+        if (atom.config.get('build-cargo.jsonErrorFormat') && buildCfg.supportsMessageFormat) {
```
Comment (alygin) [inline lib/cargo.js]: I think we also need to pass the information that we are switching off the JSON flag for this build to the `matchFunction` somehow. Otherwise it won't remove escape symbols and won't try to parse the standard output. It will break parsing for `cargo doc`, for instance.

**Comment by alygin** [comment]
Looks good to me now!

**Comment by swsnr** [comment]
Thanks for your quick help, @oli-obk and @alygin! :+1:

**Comment by oli-obk** [comment]
It's not published yet. I'm on windows right now ^^ and have no clue how to do anything useful there.

**Comment by oli-obk** [comment]
Published 1.1
